spring:
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster # 名字我在sentinel中自己取名的
      nodes: 192.168.10.32:26379, 192.168.10.32:26380, 192.168.10.32:26381